components:
  examples: {}
  headers: {}
  parameters: {}
  requestBodies: {}
  responses: {}
  schemas:
    User:
      properties:
        id:
          type: number
          format: double
        firstname:
          type: string
        lastname:
          type: string
        username:
          type: string
        usertype:
          type: string
        age:
          type: number
          format: double
        number:
          type: number
          format: double
        email:
          type: string
        password:
          type: string
        address:
          type: string
        lastlogin:
          type: string
      required:
        - id
        - firstname
        - lastname
        - username
        - usertype
        - age
        - number
        - email
        - address
        - lastlogin
      type: object
      additionalProperties: false
    IUser:
      properties:
        user:
          $ref: "#/components/schemas/User"
        token:
          type: string
      required:
        - user
        - token
      type: object
      additionalProperties: false
    signupPayload:
      description: "\"firstname\":\"Sachin\",\r\n\"lastname\": \"Patel\",\r\n\"username\": \"sachinqeep\",\r\n\"usertype\": \"Owner\" ,\r\n\"password\": sachin@1330,\r\n\"token\": \"AAAA9MUL8aI:APA91bG10taM95MS7jOdbOiPLg6rE7gBw04T5amtbQaS1KbVt2Mf5P5r801ovOOEaFVTF9U0zucknzA5Lw1VRyxtYKtkpRpMbo57Y_CQ1iMQmMJd1pFEgov0sdBgfV8UEBHZm2WY1uc8\""
      properties:
        firstname:
          type: string
        lastname:
          type: string
        username:
          type: string
        usertype:
          type: string
        password:
          type: string
        token:
          type: string
      required:
        - firstname
        - lastname
        - username
        - usertype
        - password
        - token
      type: object
      additionalProperties: false
  securitySchemes: {}
info:
  swagger: 2.0
  title: MyProject
  version: 0.0.1
  description: "Awesome project developed with TypeORM."
  contact: {}
openapi: 3.0.0
paths:
  /users/signup:
    post:
      operationId: Signup
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IUser"
      tags:
        - User
      security: []
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/signupPayload"
servers:
  - url: /
